version: '3.4'

services:
  seller:
    image: seller
    build:
      context: seller
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7001:7001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
